# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(31, 31, 21, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_conn = QtWidgets.QPushButton(self.centralwidget)
        self.btn_conn.setGeometry(QtCore.QRect(30, 80, 106, 34))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.btn_conn.setFont(font)
        self.btn_conn.setObjectName("btn_conn")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 30, 61, 32))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(201, 31, 51, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_result = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_result.setGeometry(QtCore.QRect(30, 130, 331, 91))
        self.txt_result.setObjectName("txt_result")
        self.btn_read = QtWidgets.QPushButton(self.centralwidget)
        self.btn_read.setGeometry(QtCore.QRect(210, 80, 106, 34))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.btn_read.setFont(font)
        self.btn_read.setObjectName("btn_read")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 30, 141, 32))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", " IP"))
        self.btn_conn.setText(_translate("MainWindow", "connect"))
        self.lineEdit_2.setText(_translate("MainWindow", "5025"))
        self.label_2.setText(_translate("MainWindow", " Port"))
        self.btn_read.setText(_translate("MainWindow", "read?"))
        self.lineEdit.setText(_translate("MainWindow", "169.254.4.61"))
